Prepare input component   release/v1.0
polubis/Billespace pull request #4
Opened 2022-07-05 09:50 UTC by kowalowy1234

Created an input component with 4 different variants:

- filled
- default
- error
- disabled

2022-07-05 13:29 UTC, polubis requested changes

2022-07-05 13:29 UTC, polubis commented on billennium/libs/ui/src/lib/Input/input.spec.tsx
> +    it('renders default variant', () => {
Change title to match test expect

2022-07-05 13:29 UTC, polubis commented on billennium/libs/ui/src/lib/Input/input.spec.tsx
> +    it('renders filled input', () => {
renders input

2022-07-05 13:29 UTC, polubis commented on billennium/libs/ui/src/lib/Input/input.spec.tsx
> +        render(<Input variant='default' />);
Remove default variant

2022-07-05 13:29 UTC, polubis commented on billennium/libs/ui/src/lib/Input/input.spec.tsx
> +    it('renders error variant', () => {
This test can be removed

2022-07-05 13:29 UTC, polubis commented on billennium/libs/ui/src/lib/Input/input.spec.tsx
> +        render(<Input variant='disabled'></Input>);
Change title to match - making input disabled.

toBeDisabled()

2022-07-05 13:29 UTC, polubis commented on billennium/libs/ui/src/lib/Input/input.stories.tsx
> +Disabled.args = { variant: 'disabled' };
Remove this variant from implementation - >instead of this add disabled property styles management

2022-07-05 13:29 UTC, polubis commented on billennium/libs/ui/src/lib/Input/input.tsx
> +    value?: string
value: string - always

2022-07-05 13:29 UTC, polubis commented on billennium/libs/ui/src/lib/Input/input.tsx
> +    value?: string
Add support for onChange event pass

2022-07-06 12:22 UTC, ajronn requested changes

2022-07-06 12:24 UTC, merged