Create Button component - release/v1.0
polubis/Billespace pull request #5
Opened 2022-07-05 12:22 UTC by JRKKRUPICKI

2022-07-05 13:34 UTC, polubis requested changes
Check comments

2022-07-05 13:34 UTC, polubis commented on billennium/libs/ui/src/lib/button/button.stories.tsx
> +    theme: 'filled',
theme: motive

2022-07-05 13:34 UTC, polubis commented on billennium/libs/ui/src/lib/button/button.stories.tsx
> +    backgroundColor: '#FF5A00',
This should be removed - only motive applies colors and backgrounds

2022-07-05 13:34 UTC, polubis commented on billennium/libs/ui/src/lib/button/button.stories.tsx
> +    text: 'Add',
text should be children -> ReactNode

2022-07-05 13:34 UTC, polubis commented on billennium/libs/ui/src/lib/button/button.tsx
> +const getIcon = (icon: ButtonProps['icon'], textColor: ButtonProps['textColor']) => {
Make it 100% generic like in material UI BUtton -> you can add same API format

2022-07-06 12:22 UTC, ajronn requested changes

2022-07-07 08:00 UTC, merged